version: "3.8"

services:

  vsftpd:
    container_name: vsftpd
    build: ./requirements/bonus/vsftpd
    env_file: .env
    restart: always
    volumes: 
      - html:/home/$FTP_USER/ftp
    networks:
      - net21
    ports:
      - 21:21
      - 2121-2142:2121-2142

  mariadb: 
    container_name: mariadb
    build: ./requirements/mariadb
    restart: always
    volumes: 
      - mysql:/var/lib/mysql
    networks:
      - net21

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    restart: always
    depends_on: 
      - mariadb
    volumes: 
      - html:/var/www/html
    networks: 
      - net21

  nginx:
    container_name: nginx
    build: ./requirements/nginx
    restart: always
    depends_on: 
      - wordpress
    volumes: 
      - html:/var/www/html
    networks: 
      - net21
    ports:
      - 443:443
    hostname:
      dredfort.42.fr

volumes: 
  mysql:
    name: mysql
    driver: local
    driver_opts: 
      device: /home/dredfort/data/mysql
      o: bind
      type: none
  html:
    name: html
    driver: local
    driver_opts: 
      device: /home/dredfort/data/html
      o: bind
      type: none

networks:
  net21: 
    driver: bridge